# Generated by Django 5.2.4 on 2025-08-03 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('adresse_depart', models.CharField(max_length=255)),
                ('adresse_arrivee', models.CharField(max_length=255)),
                ('date_livraison', models.DateField()),
                ('statut', models.CharField(choices=[('en_attente', 'En_attente'), ('acceptee', 'Acceptee'), ('en_cours', 'En_cours'), ('livree', 'Livree'), ('annulee', 'Annulee')], max_length=20)),
                ('date_creaton', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OffreLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_propose', models.DecimalField(decimal_places=2, max_digits=10)),
                ('est_acceptee', models.BooleanField(default=False)),
                ('date_offres', models.DateField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to='livraisons.demandelivraison')),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
